apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cnpg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"   # after operator (1), secrets (2), minio (2)
spec:
  project: default
  source:
    repoURL: https://github.com/Akorede28/Qoves_Manifest.git
    targetRevision: main
    path: manifests/postgres-cnpg
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
